### ISSUE TITLE
web development project

### ISSUE THREAD

**Issue by Melona251** [web/web.github.com#12]

**Comment by emmanuelmens2022** [comment]
index.html
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Royal King Data Hub</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <header>
        <div class="logo">
            <h1>Royal King Data Hub</h1>
        </div>
        <nav>
            <ul>
                <li><a href="#home">Home</a></li>
                <li><a href="#bundles">Data Bundles</a></li>
                <li><a href="#about">About Us</a></li>
                <li><a href="#contact">Contact</a></li>
            </ul>
        </nav>
    </header>
    <main>
        <section id="home">
            <h2>Welcome to Royal King Data Hub</h2>
            <p>Get the best data bundles at affordable prices</p>
            <button>Shop Now</button>
        </section>
        <section id="bundles">
            <h2>Our Data Bundles</h2>
            <div class="bundle-container">
                <div class="bundle">
                    <h3>Daily Bundle</h3>
                    <p>500MB - $1.99</p>
                    <button>Buy Now</button>
                </div>
                <div class="bundle">
                    <h3>Weekly Bundle</h3>
                    <p>2GB - $5.99</p>
                    <button>Buy Now</button>
                </div>
                <div class="bundle">
                    <h3>Monthly Bundle</h3>
                    <p>10GB - $19.99</p>
                    <button>Buy Now</button>
                </div>
            </div>
        </section>
    </main>
    <footer>
        <p>&copy; 2023 Royal King Data Hub. All rights reserved.</p>
    </footer>
    <script src="script.js"></script>
</body>
</html>
```

styles.css
```css
body {
    font-family: Arial, sans-serif;
    margin: 0;
    padding: 0;
    background-color: #f4f4f9;
    color: #333;
}
header {
    background-color: #2c3e50;
    color: white;
    padding: 1rem;
    display: flex;
    justify-content: space-between;
    align-items: center;
}
.logo h1 {
    margin: 0;
    color: #f39c12;
}
nav ul {
    list-style: none;
    display: flex;
}
nav ul li {
    margin-left: 1.5rem;
}
nav ul li a {
    color: white;
    text-decoration: none;
}
main {
    padding: 2rem;
}
section {
    margin-bottom: 2rem;
}
.bundle-container {
    display: flex;
    gap: 1rem;
    flex-wrap: wrap;
}
.bundle {
    background: white;
    padding: 1rem;
    border-radius: 5px;
    box-shadow: 0 2px 5px rgba(0,0,0,0.1);
    flex: 1;
    min-width: 200px;
}
button {
    background-color: #f39c12;
    color: white;
    border: none;
    padding: 0.5rem 1rem;
    border-radius: 3px;
    cursor: pointer;
}
footer {
    background-color: #2c3e50;
    color: white;
    text-align: center;
    padding: 1rem;
    position: fixed;
    bottom: 0;
    width: 100%;
}
```

script.js
```javascript
document.addEventListener('DOMContentLoaded', function() {
    // Add smooth scrolling to all links
    document.querySelectorAll('a[href^="#"]').forEach(anchor => {
        anchor.addEventListener('click', function (e) {
            e.preventDefault();
            document.querySelector(this.getAttribute('href')).scrollIntoView({
                behavior: 'smooth'
            });
        });
    });
    // Bundle purchase functionality
    document.querySelectorAll('.bundle button').forEach(button => {
        button.addEventListener('click', function() {
            const bundle = this.parentElement.querySelector('h3').textContent;
            const price = this.parentElement.querySelector('p').textContent.split(' - ')[1];
            alert(`You are about to purchase ${bundle} for ${price}. Proceed to checkout?`);
        });
    });
});
```

database.js
```javascript
// Sample database structure for Royal King Data Hub
const bundles = [
    {
        id: 1,
        name: "Daily Bundle",
        data: "500MB",
        price: 1.99,
        validity: "24 hours"
    },
    {
        id: 2,
        name: "Weekly Bundle",
        data: "2GB",
        price: 5.99,
        validity: "7 days"
    },
    {
        id: 3,
        name: "Monthly Bundle",
        data: "10GB",
        price: 19.99,
        validity: "30 days"
    }
];
const users = [
    {
        id: 1,
        name: "John Doe",
        email: "john@example.com",
        purchases: [1, 3]
    }
];
module.exports = { bundles, users };
```

server.js
```javascript
const express = require('express');
const { bundles, users } = require('./database');
const app = express();
const port = 3000;
app.use(express.static('public'));
app.get('/api/bundles', (req, res) => {
    res.json(bundles);
});
app.get('/api/bundles/:id', (req, res) => {
    const bundle = bundles.find(b => b.id === parseInt(req.params.id));
    if (!bundle) return res.status(404).send('Bundle not found');
    res.json(bundle);
});
app.listen(port, () => {
    console.log(`Royal King Data Hub server running at http://localhost:${port}`);
});
```
